/* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
#define CFLAGS cflags
/*
 * Generate CFLAGS as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char cflags[] = {
    'c','o','m','p','i','l','e','r',':',' ','a','r','m','-','l','i',
    'n','u','x','-','g','c','c',' ','-','D','D','S','O','_','D','L',
    'F','C','N',' ','-','D','H','A','V','E','_','D','L','F','C','N',
    '_','H',' ','-','D','N','D','E','B','U','G',' ','-','D','O','P',
    'E','N','S','S','L','_','T','H','R','E','A','D','S',' ','-','D',
    'O','P','E','N','S','S','L','_','N','O','_','S','T','A','T','I',
    'C','_','E','N','G','I','N','E',' ','-','D','O','P','E','N','S',
    'S','L','_','P','I','C',' ','-','D','O','P','E','N','S','S','L',
    'D','I','R','=','"','\\','"','/','h','o','m','e','/','m','o','/',
    's','h','a','r','e','/','n','e','t','c','o','n','f','2','/','l',
    'i','b','/','o','p','e','n','s','s','l','/','d','e','b','u','g',
    '/','o','u','t','p','u','t','/','s','s','l','\\','"','"',' ','-',
    'D','E','N','G','I','N','E','S','D','I','R','=','"','\\','"','/',
    'h','o','m','e','/','m','o','/','s','h','a','r','e','/','n','e',
    't','c','o','n','f','2','/','l','i','b','/','o','p','e','n','s',
    's','l','/','d','e','b','u','g','/','o','u','t','p','u','t','/',
    'l','i','b','/','e','n','g','i','n','e','s','-','1','.','1','\\',
    '"','"',' ','\0'
};
#define PLATFORM "platform: linux-generic32"
#define DATE "built on: Fri Jun 19 02:00:39 2020"
